name: "sonar_cloud_scan_github_actions"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  DemoSonarCloudSCan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install pylint pytest pytest-cov

      - name: Run PyLint and generate report
        run: |
          pylint --output-format=pylint-json --rcfile=.pylintrc ./**/*.py > pylint-report.json

      - name: Run Pytest with coverage
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Prepare SonarQube analysis
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          arguments: >
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.py
            -Dsonar.python.pylint.reportPath=pylint-report.json
            -Dsonar.python.coverage.reportPaths=coverage.xml